Manager:
  UpdatePeriod: 3600
Modules:
  Ingest:
#    - Example
#    - Maltiverse
    - CveTrendsTweets
    - CveTrendsGithub
    - CveTrendsReddit
    - PowerOutageUS
    - PowerOutageUA
    - PowerOutageCA
    - MapHubCen4Rus

  Output:
    - Splunk
#    - Elasticsearch - Not yet implemented
Databases:
  Redis:
    Host: '127.0.0.1'
    Port: '6379'
  Mongodb:
    Host: '127.0.0.1'
    Port: 27017
