Manager:
  UpdatePeriod: 300
Modules:
  Ingest:
    - Example
    - PowerOutageUS
    - PowerOutageUA
    - PowerOutageCA
    - MapHubCen4Rus
    - Maltiverse
  Output:
#   - Splunk
#    - Elasticsearch - Not yet implemented
Databases:
  Redis:
    Host: '127.0.0.1'
    Port: '6379'
  Mongodb:
    Host: '127.0.0.1'
    Port: 27017
